// Single barrel for every cross-feature reusable component. Pages should
// `import { ... } from "@/components/shared"` so each page's imports stay
// short and one-line.

export * from "./heading"
export * from "./icon"
export * from "./user-avatar"
export * from "./format-date"
export * from "./status-badge"
export * from "./breadcrumb"
export * from "./page-header"
export * from "./confirm-dialog"
export * from "./form-field"
export * from "./empty-state"
export * from "./summary-card"
export * from "./data-table"
export * from "./can"
export * from "./force-reload-watcher"
export * from "./module-placeholder"
export * from "./video-picker"
export * from "./youtube-embed"
export * from "./taka-icon"
export * from "./page-meta"
export * from "./image"
export * from "./date-range-filter"
export { default as PageMeta } from "./page-meta"
export * from "./media-picker"
export * from "./image"
